name: fraud-feature-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.1'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: make run_fraud_feature_pipeline
